create table public.posts(
    id bigint generated by default as identity primary key,

    content text
        not null
        check (char_length(content) between 1 and 300),

    empathy_count integer
        not null
        default 0
        check(empathy_count >= 0),

    cheer_count integer
        not null
        default 0
        check(cheer_count >= 0),            

    smile_count integer
        not null
        default 0
        check(smile_count >= 0),

    created_at timestamptz
        not null
        default now()    
);

alter table public.posts enable row level security;

grant select
on table public.posts
to anon, authenticated;

create policy "Anyone can read posts"
on public.posts
for select
to anon, authenticated
using (true);