create table public.reactions (
  id bigint generated by default as identity primary key,

  post_id bigint
    not null
    references public.posts(id)
    on delete cascade,

  user_id uuid
    not null
    references auth.users(id)
    on delete cascade,

  reaction_type text
    not null
    check (
      reaction_type in ('empathy', 'cheer', 'smile')
    ),

  created_at timestamptz
    not null
    default now(),

  constraint reactions_post_user_type_unique
    unique (post_id, user_id, reaction_type)
);

alter table public.reactions
enable row level security;