create table public.humor_caption_ratings (
  id bigint
    generated by default as identity
    primary key,

  caption_id bigint
    not null
    references public.humor_captions(id)
    on delete cascade,

  user_id uuid
    not null
    references auth.users(id)
    on delete cascade,

  score smallint
    not null
    check (score between 1 and 5),

  created_at timestamptz
    not null
    default now(),

  updated_at timestamptz
    not null
    default now(),

  constraint humor_caption_ratings_caption_user_unique
    unique (caption_id, user_id)
);

alter table public.humor_caption_ratings
enable row level security;

revoke all
on table public.humor_caption_ratings
from anon, authenticated;

grant select, insert, update, delete
on table public.humor_caption_ratings
to authenticated;