create table public.humor_captions (
  id bigint
    generated by default as identity
    primary key,

  prompt_id bigint
    not null
    references public.humor_prompts(id)
    on delete cascade,

  user_id uuid
    not null
    references auth.users(id)
    on delete cascade,

  content text
    not null
    check (char_length(trim(content)) between 1 and 100),

  created_at timestamptz
    not null
    default now(),

  updated_at timestamptz
    not null
    default now(),

  unique (prompt_id, user_id)
);

create index humor_captions_prompt_id_created_at_index
on public.humor_captions (prompt_id, created_at);

alter table public.humor_captions enable row level security;

revoke all
on table public.humor_captions
from anon, authenticated;

grant select
on table public.humor_captions
to anon, authenticated;

grant insert, update, delete
on table public.humor_captions
to authenticated;

create policy "Anyone can read humor captions"
on public.humor_captions
for select
to anon, authenticated
using (true);

create policy "Users can insert own humor caption"
on public.humor_captions
for insert
to authenticated
with check (
  user_id = (select auth.uid())
  and exists (
    select 1
    from public.profiles
    where profiles.id = (select auth.uid())
  )
  and exists (
    select 1
    from public.humor_prompts
    where humor_prompts.id = humor_captions.prompt_id
      and humor_prompts.starts_at <= now()
      and humor_prompts.ends_at > now()
  )
);

create policy "Users can update own active humor caption"
on public.humor_captions
for update
to authenticated
using (
  user_id = (select auth.uid())
)
with check (
  user_id = (select auth.uid())
  and exists (
    select 1
    from public.humor_prompts
    where humor_prompts.id = humor_captions.prompt_id
      and humor_prompts.starts_at <= now()
      and humor_prompts.ends_at > now()
  )
);

create policy "Users can delete own humor caption"
on public.humor_captions
for delete
to authenticated
using (
  user_id = (select auth.uid())
);

create policy "Admins can delete humor captions"
on public.humor_captions
for delete
to authenticated
using (
  exists (
    select 1
    from public.admins
    where admins.user_id = (select auth.uid())
  )
);