create table public.humor_prompts (
  id bigint
    generated by default as identity
    primary key,

  image_path text
    not null
    unique,

  alt_text text
    not null
    check (char_length(trim(alt_text)) between 1 and 100),

  starts_at timestamptz
    not null
    default now(),

  ends_at timestamptz
    not null,

  created_by uuid
    references auth.users(id)
    on delete set null,

  created_at timestamptz
    not null
    default now(),

  check (ends_at > starts_at)
);

create index humor_prompts_starts_at_index
on public.humor_prompts (starts_at desc);

alter table public.humor_prompts enable row level security;

revoke all
on table public.humor_prompts
from anon, authenticated;

grant select
on table public.humor_prompts
to anon, authenticated;

grant insert, update, delete
on table public.humor_prompts
to authenticated;

create policy "Anyone can read started humor prompts"
on public.humor_prompts
for select
to anon, authenticated
using (starts_at <= now());

create policy "Admins can read all humor prompts"
on public.humor_prompts
for select
to authenticated
using (
  exists (
    select 1
    from public.admins
    where admins.user_id = (select auth.uid())
  )
);

create policy "Admins can insert humor prompts"
on public.humor_prompts
for insert
to authenticated
with check (
  created_by = (select auth.uid())
  and exists (
    select 1
    from public.admins
    where admins.user_id = (select auth.uid())
  )
);

create policy "Admins can update humor prompts"
on public.humor_prompts
for update
to authenticated
using (
  exists (
    select 1
    from public.admins
    where admins.user_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1
    from public.admins
    where admins.user_id = (select auth.uid())
  )
);

create policy "Admins can delete humor prompts"
on public.humor_prompts
for delete
to authenticated
using (
  exists (
    select 1
    from public.admins
    where admins.user_id = (select auth.uid())
  )
);